name: Daily Profile Update

on:
  schedule:
    - cron: "30 4 * * *" # 10:00 AM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update activity file
        run: |
          echo "Last automated update: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > daily-activity.md

      - name: Commit and push
        run: |
          git config user.name "soumyadip-das-dev"
          git config user.email "soumyadipdas2679@gmail.com"

          git add daily-activity.md

          git commit -m "chore: daily profile update" || echo "No changes to commit"

          git push
